### ISSUE TITLE
Server Error when managing data

### ISSUE THREAD

**Issue by RobAndGo** [clarity-h2020/ckan#19]
This may not be an important problem, but I'll describe it here anyway.

I am logged in in CKAN under my username and I clicked on "Manage" to edit the description of a dataset (https://ckan.myclimateservice.eu/dataset/tropical-nights-tn).

After making my modifications, I clicked on "Update Dataset" and after a while the screen changed to show:

```
Server Error
An internal server error occurred
```

However, when I clicked to show the dataset again, the changes that I made were indeed there.

So my question is, is this "internal error" still significant even though my changes are still made?

**Comment by p-a-s-c-a-l** [comment]
Restarted the server. Works again.

**Comment by RobAndGo** [comment]
Now I'm afraid I get the "Server Error An internal server error occurred" whenever I try to search for a dataset. I even logged out and back in again, but still the error occurs :-(

**Comment by p-a-s-c-a-l** [comment]
I cannot reproduce the problem. Can you please provide more details, e.g. the search terms used?

**Comment by p-a-s-c-a-l** [comment]
From the logs, it seems to be related to this issue: https://github.com/ckan/ckan/issues/4431

**Comment by RobAndGo** [comment]
Hmm, now the problem is that the connection to ckan.myclimateservice.eu is not secure (in the URL bar the https is crossed out), and I cannot access it anymore. I guess this a problem only from my side, then.
This problem occurs both with chrome and firefox.

**Comment by p-a-s-c-a-l** [comment]
CKAN is down due to a [failed update](https://github.com/clarity-h2020/ckan/issues/20).

**Comment by p-a-s-c-a-l** [comment]
@RobAndGo I've upgraded CKAN to the latest version, please try again.

**Comment by RobAndGo** [comment]
Thank you @p-a-s-c-a-l!! Everything with CKAN seems to work without errors now, e.g. searching for datasets, and managing (editing) the descriptions.
