### ISSUE TITLE
Configure CKAN for CSIS 

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/ckan#2]
Add Organisations, Groups, etc. relevant for CSIS. See also https://github.com/clarity-h2020/csis/issues/3

**Comment by p-a-s-c-a-l** [comment]
Organisations for 
- common data produced and collected by CLARITY (e.g. local effects output of the [Modelling Workflow Implementation](https://github.com/clarity-h2020/csis/issues/33) and 
- for the CLARITY DCs have been created in the  [CLARTIY CKAN instance](https://ckan.myclimateservice.eu):

![grafik](https://user-images.githubusercontent.com/1788226/47485602-ba4d4c00-d83e-11e8-83ce-1469ce3bfb7e.png)

Groups for Exposure and Hazard Data have been created:

![grafik](https://user-images.githubusercontent.com/1788226/47485875-5b3c0700-d83f-11e8-9988-4551077acc0c.png)

**Comment by ghilbrae** [comment]
This issue is on hold until it's determined if further configuration is needed.

**Comment by p-a-s-c-a-l** [comment]
If we want to use CKAN also for the [Data Management Plan](https://github.com/clarity-h2020/ckan/milestone/1), we have to distinguish between:

- datasets **produced** by the project that can be released as open data and deposited in [Zenodo](https://zenodo.org/communities/clarity/) (mainly WP3 hazard data, exposure / local effects data)
- datasets **produced** by the project that cannot be made public (local data needed for the Demonstration Cases)
- datasets **used** by the project in order to the produce the aforementioned datasets (e.g. [EURO-CORDEX - EUR-11_ICHEC-EC-EARTH_KNMI-RACMO22E](https://ckan.myclimateservice.eu/dataset/euro-cordex-eur-11_ichec-ec-earth_knmi-racmo22e).

**TODO** (@p-a-s-c-a-l) : Create Groups/Organisations or Tags needed for Data Management

**Comment by ghilbrae** [comment]
@p-a-s-c-a-l I am writing a short text to keep some info on adding the T2.2 meta-data to CKAN to help people know what to do. I'd rather not write it in an email because we all know that emails tend to get lost so I'd rather write it in a wiki or something of like that. Is there a wiki or something like that in here? I could also add this info to some readme and just send the link or upload it to owncloud, but I was wondering if we already have that sort of tool. Many thanks!!

**Comment by p-a-s-c-a-l** [comment]
@ghilbrae To keep this kind of information & instructions in a central place, I recommend to use the wiki of the CSIS Management Project: https://github.com/clarity-h2020/csis/wiki

**Comment by DenoBeno** [comment]
I saw the discussion on 3000+ indices that are developed by ZAMG. Is each of these indices really a separate data set or can we group them?

**Comment by p-a-s-c-a-l** [comment]
According to  @claudiahahn 's [comment](https://github.com/clarity-h2020/ckan/issues/9#issuecomment-441967233), the datasets are published as open data in [data.ccca.ac.at](https://data.ccca.ac.at/organization/zamg)'s CKAN and **not** in our [CLARITY CKAN instance](https://ckan.myclimateservice.eu/).

So IMHO it's up to ZAMG to decide how they want to organise the datasets in their catalogue.

**Comment by p-a-s-c-a-l** [comment]
done

**Comment by p-a-s-c-a-l** [comment]
Place Frontage Logo in `/var/lib/docker/volumes/ckan_home/_data/venv/src/ckan/ckan/public/base/images` (the container!) and update ´production.ini` in `/var/lib/docker/volumes/ckan_config/_data` (the volume!).

**Comment by p-a-s-c-a-l** [comment]
![non-open-data](https://user-images.githubusercontent.com/1788226/78866436-ab148b00-7a3f-11ea-8455-f90d60f4feaa.jpg)
