### ISSUE TITLE
Clarity European Data - T2.2 - CKAN Data Collection

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/ckan#28]
We've tested the information provided in CKAN for the European wide data that is either used by several DCs or by the European Data Package with special interest on the URLs provided for the Resources in the Datasets. The results can be seen in the attached file with the following structure:

> DATASET: {dataset_name}
> > RESOURCE: {resource_name} (if there's a name)
> > > URL {ERROR | EXISTS} -> {url} (if there's one)

[clarity.txt](https://github.com/clarity-h2020/ckan/files/4096822/clarity.txt)

We are aware that there are different people or institutions in charge of these data, so lease take a look at it and ensure that the URLs and data are correct for the ones that may be yours.

**Comment by ghilbrae** [comment]
I've gone through the datasets and resources and have identified the ones that are wrong. By wrong I mean several possibilities: 
1. Missing URL
2. Existing URL that does not work
3. Existing URL that does not lead to the data

I'm attaching this new version here, please take a look at it. Most of the problematic resources are those related to climate indexes.

[clarity_wrong_stuff.txt](https://github.com/clarity-h2020/ckan/files/4102851/clarity_wrong_stuff.txt)

**Comment by claudiahahn** [comment]
Regarding the climate indices from ZAMG: in CKAN we have listed all the climate indices, which we had calculated at the time. We have to go through again and add all climate indices that we have now. We will also use your txt files and add a URL where it is missing. 
So far, the URL is pointing to the Zenodo-Clarity webpage, but there is no data yet. 
We have agreed with Pascal to do so, in order to be able to provide a list and the future place where to find the data. 
By the time we have uploaded the data, we'll insert the correct link.

**Comment by ghilbrae** [comment]
Thanks, Claudia!

**Comment by ghilbrae** [comment]
In the attached sheet I've made an analysis of the data available in CKAN and added some comments on its status. 
Please take a look at it and address the comments. I have some doubts about some datasets because they seem to cover all Europe but the link to WMS contains a bbox that covers only Naples and I don't know if this is intended for some reason or if we should change either the bbox, the name, the group to which these datasets belong to (move them to DC1, maybe?). I think these layers are related to what @negroscuro did some time ago.

If there's data no longer in use, please delete the datasets.

Also, if you have changed anything in the last couple of days, those changes may not be reflected there yet, I've been working on verifying the data for a few days now. Please, let me know and update the comments anyway.

[Status of DS+Resources available in CKAN_general.xlsx](https://github.com/clarity-h2020/ckan/files/4229965/Status.of.DS%2BResources.available.in.CKAN_general.xlsx)

**Comment by RobAndGo** [comment]
@ghilbrae I have fixed the problems with the 1971-2000 datasets in your table, as well as the datasets hot-days and snow-days.

I also noticed that I hadn't uploaded the new snow-days data to the clarity ftp. I have now put it under:
/clarityftp/europe/hazard_indices/precipitation/snow-days

**Comment by ghilbrae** [comment]
Just a reminder that once @negroscuro has finished with the calculations for the final layers we have to update Zenodo with the correct layers and also the corresponding layers in CKAN (mainly changing bbox's of layers that are currently just showing Naples and should show Europe).

**Comment by p-a-s-c-a-l** [comment]
The following datasets in CKAN are missing the  mandatory assignment to one of the [4 groups](https://ckan.myclimateservice.eu/group/):

"Dataset Title" | "organisation" | "url"
-- | -- | --
"Basins" | "CLARITY" | "https://ckan.myclimateservice.eu/dataset/basins"
"DC3 -Trees in Linz (2015)" | "CLARITY" | "https://ckan.myclimateservice.eu/dataset/dc3-trees-in-linz-2015"
"European Digital Elevation Model V1.1 / 250m resolution" | "CLARITY" | "https://ckan.myclimateservice.eu/dataset/european-digital-elevation-model-v1-1-250m-resolution"
"Hot days (HD)" | "CLARITY" | "https://ckan.myclimateservice.eu/dataset/hot-days-hd"
"Ice days (ID)" | "CLARITY" | "https://ckan.myclimateservice.eu/dataset/ice-days-id"
"Mortality" | "CLARITY" | "https://ckan.myclimateservice.eu/dataset/mortality"
"Pan-European landslide susceptibility mapping: ELSUS Version 2" | "CLARITY" | "https://ckan.myclimateservice.eu/dataset/pan-european-landslide-susceptibility-mapping-elsus-version-2"
"RESCCUE - Barcelona Traffic Impact" | "CLARITY" | "https://ckan.myclimateservice.eu/dataset/resccue-barcelona-traffic-impact"
"RESCCUE - Bristol Adaptation Strategies" | "CLARITY" | "https://ckan.myclimateservice.eu/dataset/resccue-bristol-adaptation-strategies"
"RESCCUE - Bristol Flood Hazard Maps" | "CLARITY" | "https://ckan.myclimateservice.eu/dataset/resccue-bristol-flood-hazard-maps"
"RESCCUE - Daily Maximum Surface Air Temperature climatic data for Barcelona" | "CLARITY" | "https://ckan.myclimateservice.eu/dataset/resccue-daily-maximum-surface-air-temperature-climatic-data-for-barcelona"
"RESCCUE - Pluvial flood - Hazard Pedestrian BASELINE T = 50" | "CLARITY" | "https://ckan.myclimateservice.eu/dataset/resccue-pluvial-flood-hazard-pedestrian-baseline-t-50"
"RESCCUE - precipitation climatic data for Barcelona" | "CLARITY" | "https://ckan.myclimateservice.eu/dataset/resccue-precipitation-climatic-data-for-barcelona"
"RESCCUE - prsn climatic data for Barcelona" | "CLARITY" | "https://ckan.myclimateservice.eu/dataset/resccue-prsn-climatic-data-for-barcelona"
"Sports" | "CLARITY" | "https://ckan.myclimateservice.eu/dataset/sports"
"Streams" | "CLARITY" | "https://ckan.myclimateservice.eu/dataset/streams"
**"Test meteo dataset"** | "CLARITY" | "https://ckan.myclimateservice.eu/dataset/test-meteo-dataset2"

@negroscuro @ghilbrae Please update datasets.

**Comment by RobAndGo** [comment]
Hi @p-a-s-c-a-l, sorry, but I wasn't aware of these groups. :-(
I have updated them for the "Hot days" and "ice days".

**Comment by LenaStr** [comment]
HI,

I have now made the update.

/Lena

Från: RobAndGo [mailto:notifications@github.com]
Skickat: den 2 april 2020 09:02
Till: clarity-h2020/ckan
Kopia: Strömbäck Lena; Assign
Ämne: Re: [clarity-h2020/ckan] Clarity European Data - T2.2 - CKAN Data Collection (#28)


Hi @p-a-s-c-a-l<https://github.com/p-a-s-c-a-l>, sorry, but I wasn't aware of these groups. :-(
I have updated them for the "Hot days" and "ice days".

**Comment by p-a-s-c-a-l** [comment]
Please have a look at the Data Management [Validation Report](https://github.com/clarity-h2020/ckan/files/4427067/clarity.docx) and correct all errors.

**Comment by claudiahahn** [comment]
@p-a-s-c-a-l, @ghilbrae, I have updated some entries in CKAN and entered one missing index on Tuesday (now 3 wind indices with correct link to Zenodo: Fmax, Torro17, 98percentile of daily max wind speed). Just that you know.

**Comment by p-a-s-c-a-l** [comment]
Updated validation report: [clarity.docx](https://github.com/clarity-h2020/ckan/files/4522980/clarity.docx)

Pan-European hazard  datasets are fine, Hazard Local Effects Input Layers [will be updated](https://github.com/clarity-h2020/ckan/issues/31) when all layers have been recalculated (again).

There are still some issues related to the [Resccue Data Package](https://github.com/clarity-h2020/data-package/issues/57) and several resources related to [DC4](https://github.com/clarity-h2020/ckan/issues/27), e.g.

- https://ckan.myclimateservice.eu/dataset/fire-behaviour
- https://ckan.myclimateservice.eu/dataset/spanish-fire-forcast
