### ISSUE TITLE
CKAN seems to be down

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/ckan#29]
CKAN has been unresponsive this morning.

For one, it complains about the connection not being private (no https) and then it just returns error 503.

Is some work being done with this server?

**Comment by p-a-s-c-a-l** [comment]
Sorry, I stopped the containers temporarily to create some backups. It's working again.

On Monday morning I want to move CKAN to our [new server](https://github.com/clarity-h2020/csis/issues/113#issuecomment-583256043). It will be temporarily available under a different URL (http://ckan.clarity.cismet.de/) until the [.myclimateservices.eu DNS entries](https://github.com/clarity-h2020/csis/issues/23#issuecomment-581776771) have been updated.

**Comment by ghilbrae** [comment]
No problem! Thanks for the info!!
