### ISSUE TITLE
Meta-Data Harmonisation

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/ckan#5]
We should harmonise the different meta-data schemas used through the project when registering datasets meta-data for the [Data Management Plan](https://github.com/clarity-h2020/ckan/milestone/1) and the [Catalogue of local data sources and sample datasets](https://github.com/clarity-h2020/csis/milestone/8) in [CLARITY's CKAN Catalogue](https://ckan.myclimateservice.eu/):

**ZAMG HazardData Meta-Data:**
- Example: https://github.com/clarity-h2020/ckan/issues/8

**CLARITY Data Package Meta-Data:**
- Specification: https://github.com/clarity-h2020/data-package/wiki/Specification
- Usage: https://csis.myclimateservice.eu/

**CLARITY Data Management Meta-Data**
- Specification: [Data Management Plan Annex](https://repository.atosresearch.eu/owncloud/index.php/apps/files/ajax/download.php?dir=%2FCLARITY%2FWP7%20Project%20Management%2FDeliverables%2FD7.8%20Data%20Management%20Plan%20v1&files=D7.8%20Data%20Management%20Plan%20v1.0-final.docx)
- Usage: http://cat.clarity-h2020.eu/demo_cases/datasets

**D2.2 Data Collection Meta-Data**
- Specification / Usage: [DataCollection.xls](https://repository.atosresearch.eu/owncloud/index.php/apps/files/ajax/download.php?dir=%2FCLARITY%2FWP2%20Demonstration%20and%20Validation%2FT2.2%20Demonstrator-specific%20data%20collection&files=D2.2_DataCollection_tracking_20180925_PLINIVS.xls)

**CKAN Default Meta-Data Scheme**

- Specification: https://ckan.org/portfolio/metadata/
- Usage Example: [EURO-CORDEX - EUR-11_ICHEC-EC-EARTH_KNMI-RACMO22E ](https://ckan.myclimateservice.eu/dataset/euro-cordex-eur-11_ichec-ec-earth_knmi-racmo22e)

**Zenodo Meta-Data** (the open data long-term archive we want to use for depositing open data produced by the project)
- Specification: https://schema.datacite.org/
- Usage: https://zenodo.org/

There are 3 realistic options (apart from [implementing](https://docs.ckan.org/en/2.8/extensions/adding-custom-fields.html) just another harmonised meta-data schema in ckan):

1. use ['extra'](https://docs.ckan.org/en/latest/api/index.html#ckan.logic.action.create.package_create) fields. the dataset's extras (optional), extras are arbitrary (key: value) metadata items that can be added to datasets
2. put the meta-data into the description field
3. upload additional .json,xml,txt meta-data files together with resource file or put them in one .zip file

**Comment by ghilbrae** [comment]
FYI, we are preparing some translation spreadsheet-CKAN for T2.2, we'll be sending the info tomorrow.

**Comment by p-a-s-c-a-l** [comment]
1. Requires the user to add numerous extra fields to the dataset meta-data
2. Requires the ability to put html or markdown formatted text into the description field of ckan
3. Requires the user to upload the meta-data files as additional resource of the datasets

**Comment by p-a-s-c-a-l** [comment]
For adding WP2 datasets and mapping D2.2 Data Collection Meta-Data to CKAN see [T2.2 Data Management Spreadsheet to CKAN HOW TO](https://github.com/clarity-h2020/csis/wiki/T2.2-Data-Management---Spreadsheet-to-CKAN-HOW-TO)

**Comment by p-a-s-c-a-l** [comment]
For [adding Data Management Plan v1 Datasets](https://github.com/clarity-h2020/ckan/issues/6) we follow option 2) and put the markdown-formatted contents of the initial [Data Survey](http://cat.clarity-h2020.eu/demo_cases/datasets) into the description field.

**Comment by p-a-s-c-a-l** [comment]
No further harmonisation **of meta-data** planned.
