### ISSUE TITLE
Update Catalogue Information

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/ckan#7]
Update the *about* and *summary* pages and include information related to Data Management in CLARITY. In particular, provide links to CLARITY's
- [Data Management Policy](https://zenodo.org/record/1491532)
- [CLARITY Project in OpenAIRE](https://explore.openaire.eu/search/project?projectId=corda__h2020::42171f776c336559bebf4a4ec817d79a)
- [CLARITY Community in Zenodo](https://zenodo.org/communities/clarity/)
- other **institutional repositories** that host CLARITY open data, like [data.ccca.ac.at](https://data.ccca.ac.at/organization/zamg)

**Comment by DenoBeno** [comment]
I am not sure if our data management plan is considered accepted at this point by the commission or not. Can you add a disclaimer saying that the deliverable should be considered a "working draft" for now (or such)?

**Comment by p-a-s-c-a-l** [comment]
OK. I'll create a separate .docx anyway that gives short summary (per WP) of the contents of the CLARITY CKAN and [ZAMG's CKAN](https://github.com/clarity-h2020/ckan/issues/9#issuecomment-442048699).

**Comment by p-a-s-c-a-l** [comment]
done
